# Revisiting Jupyter Notebook

Questions:
1. Are we going to provide a template for contributors?
2. JupyterLab?


# Code-Style in Notebook

1. Install black (uncompromising Python code formatter) for notebook, and `%load_ext nb_black` to the 1st cell of your notebook:

```bash
$ conda install -c conda-forge nb_black
```

In [1]:
%load_ext nb_black

<IPython.core.display.Javascript object>

In [2]:
import numpy as np

<IPython.core.display.Javascript object>

In [6]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a + b)

[5 7 9]


<IPython.core.display.Javascript object>

In [4]:
c = a + b + b
c

array([ 9, 12, 15])

<IPython.core.display.Javascript object>

In [7]:
d = a * b
print(d)

[ 4 10 18]


<IPython.core.display.Javascript object>

## Testing Notebook

Run the notebook and make sure that:
 1) it generates the same output as has been stored
 2) it does not generate any errors

```
$ conda install -c conda-forge nbval
$ py.test –nbval  notebook_file.ipynb
```


## Using Notebook & Git

## Jupyter Notebook Extensions
Goal: Improve productivity in the notebook environemnt because out-of-the-box notebooks notoriously lack features.