In [1]:
"""Exercise in linear algebra and matrix mechanics."""

__authors__ = "D. A. Sirianni"
__credits__ = ["Daniel G. A. Smith"]
__email__   = ["sirianni.dom@gmail.com"]

__copyright__ = "(c) 2008-2019, The Psi4Education Developers"
__license__   = "BSD-3-Clause"
__date__      = "2019-11-18"

# Instructor Notes

#### Activity Summary
This activity is intended to review the basics of matrix operations and to introduce generalized tensor
contractions, Einstein summation convention, and the use of NumPy library functions to perform contractions
efficiently.

#### Prerequisite Knowledge
This activity assumes that the students are familiar with basic matrix operations and linear algebra, but not
at the level of a full semester-long course.  This activity also assumes all the [standard python pre-requisites
of all Psi4Education labs](https://admiring-tesla-08529a.netlify.com/posts/psi4jupyter_labs/).  

#### Learning ojbectives
By the end of this lesson, students will be able to:
1. Define common matrix operations (inner, outer, direct products) in summation notation,
2. Implement matrix multiplication by hand in Python,
3. Expand/contract tensor expressions using Einstein summation convention,
4. Leverage library functions to implement tensor contractions from written formulas, and
5. Justify strengths and weaknesses of the various tensor contraction engines.

#### Expected Schedule
This exercise is expected to require a full 3-hour laboratory period.

Authors: Dominic A. Sirianni (sirianni.dom@gmail.com; [ORCID: 0000-0002-6464-0213](https://orcid.org/0000-0002-6464-0213) )

# Motivation

Differential equations, which seek to find an unknown function through its relationship to its own derivative(s),
are a universal language in the physical sciences and engineering which describe everything from electron
dynamics to problems in civil engineering and aeronautics.  For advancements in these applications, solving
differential equations accurately and efficiently is of crucial importance.  Unfortunately, many of these
expressions do not have an analytical solution, meaning that only approximate solutions are available.  

One of the most significant advantages of scientific computing is the efficiency with which computers
can perform linear algebra operations and solve linear algebra expressions.  Therefore, in order to study the
multitude of physical phenomena described by differential equations, an understanding of scientific computing and
numerical linear algebra is of critical importance.


## Representing Vectors & Matrices in Python

A vector is simply an ordered collection of scalar components, and a matrix is simply an ordered collection of
row (or column) vectors.  Therefore, we can represent these objects with any Python type that is a similarly
ordered collection, including a `list` or `tuple`.  Often, we would like to be able to modify the elements of
these objects, so generally using a `list` is preferred.

In [84]:
# ==> Arrays as Lists <==
# Define a length-5 vector v
v = [1, 2, 3, 4, 5]
# Define two 3x3 matrices, A & B, as lists of row vectors
A = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
B = [[10, 11, 12], [13, 14, 15], [16, 17, 18]]

## Array Operations: Scalars, Vectors, & Marices
For matrices **A** and **B** and constants $r$ and $s$, 
#### Matrix Addition
$${\bf A} + {\bf B} = \begin{pmatrix}
a & b\\
c & d
\end{pmatrix} + \begin{pmatrix}
e & f\\
g & h
\end{pmatrix} = \begin{pmatrix}
a + e & b + f\\
c + g & d + h
\end{pmatrix}
$$

#### Scalar Multiplication & Addition
$$r\cdot{\bf A} + s= r\cdot\begin{pmatrix}
a & b\\
c & d
\end{pmatrix} + s = \begin{pmatrix}
r\cdot a + s & r\cdot b + s \\
r\cdot c + s & r\cdot d + s 
\end{pmatrix}
$$

#### Matrix Multiplication

![Matrix multiplication](media/matmul.png)
$${\bf C} = \sum_{i=1}^{M}\sum_{k=1}^{N}\sum_{j=1}^{P}A_{ik}B_{kj}$$

In [21]:
# ==> Implement the matrix product of A x B using Python for-loops <==

import numpy as np

C = np.zeros((3,3))

for i in range(3):
    for j in range(3):
        for k in range(3):
            C[i, j] += A[i][k] * B[k][j]
            
print(C)


[[ 84.  90.  96.]
 [201. 216. 231.]
 [318. 342. 366.]]


### Using Built-In NumPy Functions

1. `numpy.einsum()`
2. `numpy.dot()`

In [2]:
import numpy as np

In [7]:
# ==> Create two (3,3) matrices <==
np_A = np.array(A)
np_B = np.array(B)

In [78]:
# ==> Define a function which is reusable <==
def matmul(a,b):
    # Get the shapes of A & B
    ai, ak = a.shape # n_rows * n_cols
    bk, bj = b.shape
    assert ak==bk # Check that the matrices are compatible
    # Create (ai, bj) matrix to store the result
    C = np.zeros((ai, bj))
    for i in range(ai):
        for k in range(bk):
            for j in range(bj): # or br
                C[i,j] += a[i,k] * b[k,j]
                
    return C

In [24]:
%timeit matmul(np_A, np_B)

10000 loops, best of 5: 28.2 µs per loop


In [23]:
%timeit np_A.dot(np_B)

The slowest run took 45.73 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 845 ns per loop


## Tensor Contractions: Generalized Matrix Multiplication

The way we've defined the matrix product, we may only multiply compatible arrays, which share the same "inner"
dimensions, which yields a matrix with the "outer" dimensions.  By using the definition of matrix multiplication
written as a triple summation, however, we can generalize this operation to yield other shapes as well.

Given two (3, 5) rectangular matrices $A$ and $B$, let's consider the following expressions:

1. "Inner" Product
$${\bf M} = A\times B^{\rm T}$$

2. "Outer" Product
$${\bf N} = A^{\rm T}\times B$$



In [52]:
# ==> Evaluate above contractions w/ np.dot() <==
# Define random matrices
A = np.random.random((3, 5))
B = np.random.random((3, 5))

# Inner product
M = A.dot(B.T)
print(f"The shape of the inner product is {M.shape}")
print(M)

# Outer product
#N = outer_product(A,B.T)
N = A.T.dot(B)
print(f"The shape of the outer product is {N.shape}")
print(N)

The shape of the inner product is (3, 3)
[[0.92698283 1.3011426  0.69503391]
 [1.67945146 2.21216242 1.6315874 ]
 [1.75203946 1.99938055 1.15459474]]
The shape of the outer product is (5, 5)
[[0.87283543 1.0290475  0.28069123 0.80811015 0.67448671]
 [1.4129747  1.27405327 0.42100785 0.82428539 0.77541586]
 [1.5138977  1.58186086 0.57174475 1.05331082 0.97810838]
 [1.08598248 1.34031071 0.63620106 0.81025977 0.81093006]
 [1.21828095 1.30183175 0.63003594 0.72328401 0.76484676]]


For these two products, the dimensions of our two arrays are the same, even though they're rectangular.  What
if only one dimension is shared, however?  Take for example a (4, 2) array $C$ and a (4, 5) array $D$.  Now, only
an "inner" product between $C$ and $D$ makes sense, resulting in a (2, 5) array $R$:

$${\bf R}_{2\times 5} = {\bf C}^{T}\times {\bf D}$$


In [62]:
C = np.random.random((4, 2))
D = np.random.random((4, 5))

# Evaluate inner product
R = C.T.dot(D)
print(R)

[[1.45710931 2.44675519 1.96380962 1.38912083 1.59138581]
 [1.49395369 2.57284262 1.95392226 1.3892631  1.67327372]]


### Einstein Summation Convention

Just like the matrix multiplication, we may write these tensor contractions as summations.  To avoid writing out
the sums, however (because we're lazy), we will introduce the _Einstein summation convention_:
>In a tensor expression, repeated indices are contracted over.

Therefore, we can rewrite each of the above tensor contractions more compactly as:
1. Inner product:
$$C_{ij} = \sum_{i=1}^{M}\sum_{k=1}^{N}\sum_{j=1}^{P}A_{ik}B_{kj} = A_{ik}B_{kj}$$

2. Outer product:
$$C_{kk} = \sum_{i=1}^{M}\sum_{k=1}^{N}\sum_{j=1}^{P}A_{ki}B_{jk} = A_{ki}B_{jk}$$

Other than shortening the amount being written in each of these expressions, the Einstein summation convention
also provides information directly about the shapes of the resulting array. To illustrate this, consider the
following products, with example array shapes:

| Einstein Summation | Example Shape |
|--------------------|---------------|
| $A_{ik}B_{kj}\rightarrow C_{ij}$ | (2, 3) x (3, 4) $\rightarrow$ (2, 4) |
| $A_{ij}B_{ik}\rightarrow C_{jk}$ | (2, 8) x (2, 5) $\rightarrow$ (8, 5) |

We've seen that we can use `np.dot()` to evaluate each of these contractions, however this approach is sometimes
confusing, and doesn't seem to offer the same level of information as is provided in Einstein summation.  Plus,
since many relevant equations are written down using the Einstein convention, wouldn't it be convenient if we
could just use this convention directly when evaluating the contractions numerically?

Well, we're in luck! NumPy offers a function specifically to do this, called `np.einsum()`, which takes as an
argument the index "map" which defines the contraction, just like we've seen in the table above:

| Einstein Summation | Example Shape | `np.einsum()` Call |
|--------------------|---------------|--------------------|
| $A_{ik}B_{kj}\rightarrow C_{ij}$ | (2, 3) x (3, 4) $\rightarrow$ (2, 4) | `np.einsum('ik,kj->ij', A, B)` |
| $A_{ij}B_{ik}\rightarrow C_{jk}$ | (5, 2) x (2, 5) $\rightarrow$ (5, 8) | `np.einsum('ij,ik->jk', A, B)` |




In [69]:
print(A.shape, B.shape, C.shape, D.shape)

print(np.einsum('ij,ik->jk', A, B))
print(np.einsum('ik,jk->ij', A, D))
print(np.einsum('ij,ij->', A, B))

(3, 5) (3, 5) (4, 2) (4, 5)
[[0.87283543 1.0290475  0.28069123 0.80811015 0.67448671]
 [1.4129747  1.27405327 0.42100785 0.82428539 0.77541586]
 [1.5138977  1.58186086 0.57174475 1.05331082 0.97810838]
 [1.08598248 1.34031071 0.63620106 0.81025977 0.81093006]
 [1.21828095 1.30183175 0.63003594 0.72328401 0.76484676]]
[[0.75451605 0.95647948 1.59433061 1.12403862]
 [2.20556582 2.1955936  2.65288728 1.45724928]
 [1.72562669 1.67415621 2.77309128 1.84641186]]
4.29373998089209


The single biggest benefit to `np.einsum` is how explicitly the contractions are represented.  As an example,
consider the following contractions between a rank-4 tensor $I$ and a rank-2 tensor $D$:
$$J_{pq} = I_{pqrs}D_{rs}$$
$$K_{pq} = I_{prqs}D_{rs}$$

While it is not obvious how to perform these contractions with `np.dot()`, these operations are simple to
translate into calls to `np.einsum()`.  In the cell below, try it out:

In [72]:
I = np.random.random((12, 12, 12, 12))
D = np.random.random((12,12))

J = np.einsum('pqrs,rs->pq', I, D)
K = np.einsum('prqs,rs->pq', I, D)
print(J.shape, K.shape)

(12, 12) (12, 12)


### Computational Efficiency

In [82]:
# ==> Declare large-ish matrices for timings <==

A = np.random.random((500,500))
B = np.random.random((500,500))

# Our hand-written matrix multiply
print('Timing our matrix multiply:')
%time mm_C = matmul(A, B)

# Einsum
print('Timing np.einsum:')
%time es_C = np.einsum('ik,kj->ij', A, B)

# Dot product
print('Timing np.dot:')
%time dot_C = A.dot(B)


Timing our matrix multiply:
CPU times: user 1min 43s, sys: 310 ms, total: 1min 44s
Wall time: 1min 44s
Timing np.einsum:
CPU times: user 43.3 ms, sys: 1.45 ms, total: 44.8 ms
Wall time: 46.3 ms
Timing np.dot:
CPU times: user 13.7 ms, sys: 4.73 ms, total: 18.4 ms
Wall time: 11.8 ms


### Comparing Contraction Engines

##### Student Answer Box
1. Based on the experiences and use cases above, order the three contraction engines based on the following
factors from "best" to "worst".  Justify your orderings.
    1. Computational efficiency (speed)
        - `np.dot` >  `np.einsum` >>> manual Python loops
        - The timings are pretty clear.
    2. Code clarity & readability
        - `np.einsum` > `np.dot` $\sim$ manual Python loops
    3. Engine flexibility
        - `np.einsum` > `np.dot` >>> manual Python loops
    
2. Based on your orderings, recommend a use case for each contraction engine.  Justify your recommendation.
    1. Manual Python loops
        - Either don't use or only use to teach the matrix multiplication formula.
    2. NumPy Einsum
        - Complicated contraction, etc. and want to be explicit while maintaining decent efficiency
    3. NumPy Dot
        - Any time that readability is not as important as speed.

In [1]:
print(2 + 5)

8
